services:
#    srvdv_server.example:
#        class: SRVDV\ServerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirect.after.login:
        class: SRVDV\ServerBundle\Redirection\AfterLoginRedirection
        arguments: [@router]

    app.form.registration:
        class: SRVDV\ServerBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: srvdv_user_registration }
    app.form.profile:
        class: SRVDV\ServerBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: srvdv_user_profile }
    app.form.update:
        class: SRVDV\ServerBundle\Form\UpdateType
        tags:
            - { name: form.type, alias: srvdv_user_update }
    import.csvtoarray:
        class: SRVDV\ServerBundle\Services\ConvertCsvToArray         
    